{"level":"error","message":"Status code: 500. Internal Server Error [getAllUsers] RepositoryNotFoundError: No repository for \"UserEntity\" was found. Looks like this entity is not registered in current \"default\" connection?","stack":"Error: Internal Server Error [getAllUsers] RepositoryNotFoundError: No repository for \"UserEntity\" was found. Looks like this entity is not registered in current \"default\" connection?\n    at IntErrorWrap (/usr/app/src/common/internal-error-wrapper.ts:9:11)\n    at getAll (/usr/app/src/resources/users/user.controller.ts:26:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":500,"timestamp":"2022-01-15 13:10:04:104"}
{"level":"error","message":"Status code: 500. Internal Server Error [getAllUsers] QueryFailedError: relation \"users\" does not exist","stack":"Error: Internal Server Error [getAllUsers] QueryFailedError: relation \"users\" does not exist\n    at IntErrorWrap (/usr/app/src/common/internal-error-wrapper.ts:9:11)\n    at getAll (/usr/app/src/resources/users/user.controller.ts:26:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":500,"timestamp":"2022-01-15 13:12:15:1215"}
{"level":"error","message":"Status code: 500. Internal Server Error [getAllUsers] QueryFailedError: relation \"users\" does not exist","stack":"Error: Internal Server Error [getAllUsers] QueryFailedError: relation \"users\" does not exist\n    at IntErrorWrap (/usr/app/src/common/internal-error-wrapper.ts:9:11)\n    at getAll (/usr/app/src/resources/users/user.controller.ts:26:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":500,"timestamp":"2022-01-15 13:13:20:1320"}
{"level":"error","message":"Status code: 500. Internal Server Error [getAllUsers] QueryFailedError: relation \"users\" does not exist","stack":"Error: Internal Server Error [getAllUsers] QueryFailedError: relation \"users\" does not exist\n    at IntErrorWrap (/usr/app/src/common/internal-error-wrapper.ts:9:11)\n    at getAll (/usr/app/src/resources/users/user.controller.ts:26:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":500,"timestamp":"2022-01-15 13:13:22:1322"}
{"level":"error","message":"Status code: 500. Internal Server Error [postUser] QueryFailedError: relation \"users\" does not exist","stack":"Error: Internal Server Error [postUser] QueryFailedError: relation \"users\" does not exist\n    at IntErrorWrap (/usr/app/src/common/internal-error-wrapper.ts:9:11)\n    at postUser (/usr/app/src/resources/users/user.controller.ts:78:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":500,"timestamp":"2022-01-15 13:13:47:1347"}
{"level":"error","message":"Status code: 500. Internal Server Error [postUser] QueryFailedError: relation \"users\" does not exist","stack":"Error: Internal Server Error [postUser] QueryFailedError: relation \"users\" does not exist\n    at IntErrorWrap (/usr/app/src/common/internal-error-wrapper.ts:9:11)\n    at postUser (/usr/app/src/resources/users/user.controller.ts:78:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":500,"timestamp":"2022-01-15 13:14:08:148"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:18:03:183"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:19:13:1913"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:19:59:1959"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:40:44:4044"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:40:55:4055"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:41:07:417"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:41:20:4120"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:41:32:4132"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:41:43:4143"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:41:54:4154"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:42:05:425"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:42:18:4218"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:43:49:4349"}
{"level":"error","message":"Unhandled rejection QueryFailedError: relation \"users\" does not exist","timestamp":"2022-01-15 13:46:53:4653"}
{"level":"error","message":"Status code: 500. Internal Server Error [putTask] QueryFailedError: insert or update on table \"tasks\" violates foreign key constraint \"FK_8a75fdea98c72c539a0879cb0d1\"","stack":"Error: Internal Server Error [putTask] QueryFailedError: insert or update on table \"tasks\" violates foreign key constraint \"FK_8a75fdea98c72c539a0879cb0d1\"\n    at IntErrorWrap (/usr/app/src/common/internal-error-wrapper.ts:9:11)\n    at putTask (/usr/app/src/resources/tasks/task.controller.ts:162:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":500,"timestamp":"2022-01-15 17:50:16:5016"}
